Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment_8_Joisah_Sarles.Models;

namespace Assignment_8_Joisah_Sarles.Components
{

    //The View Component for the cart summary
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using Assignment_8_Joisah_Sarles.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment_8_Joisah_Sarles.Components
{
    // NavigationMenu View Compnent, outputs a partial view for the navigation and allows for the highlighting of the category currently selected
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IFamazonRepo _repo;

        public NavigationMenuViewComponent (IFamazonRepo r)
        {
            _repo = r;
        }
         
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(
                _repo.books
                .Select(x => x.category)
                .Distinct()
                .OrderBy(x => x)
                );
        }
    }
}

Views/Shared/BookInfo.cshtml
@model Book

@* The partial view for book info *@

<div class="card card-outline-primary m-1 p-1">
    <h5>
        @Model.title
    </h5>
    <p>
        Author: @Model.authorFirst @Model.authorMiddle @Model.authorLast
    </p>
    <p>
        Publisher: @Model.publisher
    </p>
    <p>
        ISBN: @Model.isbn
    </p>
    <p>
        Classification/Category: @Model.classification, @Model.category
    </p>
    <p>
        # of Pages: @Model.pages
    </p>
    <p>
        Price: $@Model.price
    </p>
    @*Added the add to cart button form*@
    <form id="@Model.bookId" asp-page="/ShoppingCart" method="post">
        <input type="hidden" asp-for="bookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            <button type="submit" class="btn-success btn-sm">Add to Cart</button>
        </span>
    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ViewData["Assignment"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="~/Y-favicon.ico" />
    <script src="https://kit.fontawesome.com/9873785e23.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-brand text-white">@ViewData["Assignment"]</div>
            </div>

            @* Added the cart summary widget *@
            <div class="col-6 text-right navbar-brand text-white">
                <vc:cart-summary />
            </div>
        </nav>
    </header>
    <div class="container">

        @* Added the View Component here for the navigation menu*@
        <div class="row m-1 p-1">
            <div class="col-3">
                <vc:navigation-menu />
            </div>
            <div class="col-1">
            </div>
            <div class="col-6 text-center">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted text-white text-right bg-dark">
        <div class="container">
            &copy; 2021 - @ViewData["Assignment"]
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>