Pages/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment_8_Joisah_Sarles.Infrastructure;
using Assignment_8_Joisah_Sarles.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Assignment_8_Joisah_Sarles.Pages
{

    //Page model for Shopping cart, used throughout the session, can add a cart item or remove one. 
    public class ShoppingCartModel : PageModel
    {
        private IFamazonRepo _repo;

        public ShoppingCartModel (IFamazonRepo repo, Cart cartservice)
        {
            _repo = repo;
            Cart = cartservice;
        }

        public Cart Cart { get; set; }

        public string ReturnUrl { get; set; }


        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";

        }

        public IActionResult OnPost(long bookId, string returnUrl)
        {
            Book book = _repo.books.FirstOrDefault(p => p.bookId == bookId);

            Cart.AddItem(book, 1);

            return RedirectToPage(new {returnUrl = returnUrl});
        }

        public IActionResult OnPostRemove(long bookId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(p =>
                p.Book.bookId == bookId).Book);
            return RedirectToPage(new { returnUrl = returnUrl });
        }


    }
}

Pages/ShoppingCart.cshtml
@page
@model Assignment_8_Joisah_Sarles.Pages.ShoppingCartModel
@{
    ViewData["Title"] = "Shopping Cart";
    ViewData["Dash"] = "-";
    //ViewData["SubTitle"] = "Shopping Cart";
    ViewData["Assignment"] = "Assignment_8_Joisah_Sarles";
}


@* Shoppiong cart View, puts it in a nice table format
    You can also remove the items, and continue shopping with the button
    *@
<div class="container">
    <div class="row">
        <h2>
            Your Cart
        </h2>
    </div>
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right"></th>
                    <th class="text-right">Subtotal</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var line in Model.Cart.Lines)
                {
                <tr>
                    <td class="text-left">
                        @line.Book.title

                    </td>
                    <td class="text-center">
                        @line.Quantity
                    </td>
                    <td class="text-right">
                        @((line.Book.price.ToString("c")))
                    </td>
                    <td class="text-right">
                        @((@line.Quantity * @line.Book.price).ToString("c"))
                    </td>
                    <td>

                        @* Remove button *@
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="bookId"
                                   value="@line.Book.bookId" />
                            <input type="hidden" name="returnUrl"
                                   value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                Remove
                            </button>
                        </form>
                    </td>
                </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    @* Calculates the toatl and displays it *@
                    <td colspan="3" class="text-right">
                        Total:
                    </td>
                    <td class="text-right">
                        @Model.Cart.ComputeTotalSum().ToString("c")
                    </td>
                    <td>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="row text-center">
        <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    </div>
</div>